default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  username: root
  password:
  host: postgres
  port: 5432

development:
  <<: *default
  database: dev_sample_db

test:
  <<: *default
  database: test_sample_db

production:
  <<: *default
  database: prod_sample_db
